[env:esp32dev]
platform      = espressif32
board         = esp32dev
framework     = arduino
monitor_speed = 115200

; Cambia COM6 por el puerto de tu equipo (ej: /dev/ttyUSB0 en Linux/Mac)
upload_port   = COM6
monitor_port  = COM6

lib_deps =
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson  @ ^6.21
